# To be able to use pnpm, npm needs to be disabled.
[build.environment]
NPM_FLAGS = "--prefix=/dev/null"

# Since routing is handled by SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Not caching Service Worker for better install experience
[[headers]]
for = "/sw.js"

cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
